# Generated by Django 6.0.4 on 2026-04-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
    ]
