services:
  - type: web
    name: expense-tracker-web
    runtime: python
    plan: starter
    buildCommand: bash build.sh
    startCommand: python -m gunicorn expense_tracker.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString

databases:
  - name: expense-tracker-db
    plan: basic-256mb
